// generated by testdata/selfhost_e2e.dot via stdlib/codegen.dot
#include <stdio.h>
#include <math.h>
#include <stdint.h>

typedef struct {
    double x;
    double y;
} DotPoint;

int64_t Dot_add(int64_t a, int64_t b) {
    return (a + b);
}

double Dot_Point_distance(DotPoint* self, DotPoint other) {
    double dx = (self->x - other.x);
    double dy = (self->y - other.y);
    return sqrt(((dx * dx) + (dy * dy)));
}

int64_t Dot_sum_to__int(int64_t n) {
    int64_t total = 0;
    for (int64_t i = 1; i <= n; i += 1) {
        total = (total + i);
}
    return total;
}

int64_t Dot_classify(int64_t x) {
    if ((x == 0)) {
return 0;
} else if ((x == 1)) {
return 1;
} else if ((x == 2)) {
return 2;
} else {
return -1;
}
}

int main(void) {
    DotPoint p = ((DotPoint){ .x = 3.0, .y = 4.0 });
    DotPoint q = ((DotPoint){ .x = 0.0, .y = 0.0 });
    double d = Dot_Point_distance(&p, q);
    int64_t m = (((d > 5.0)) ? (1) : (0));
    int64_t k = 42;
    printf("add(2,3)=%lld\n", (long long)Dot_add(2, 3));
    printf("dist=%f\n", d);
    printf("dist_big=%lld\n", (long long)m);
    printf("k=%lld\n", (long long)k);
    printf("sum_to(10)=%lld\n", (long long)Dot_sum_to__int(10));
    printf("classify(0)=%lld\n", (long long)Dot_classify(0));
    printf("classify(2)=%lld\n", (long long)Dot_classify(2));
    printf("classify(9)=%lld\n", (long long)Dot_classify(9));
    return 0;
}
